### ISSUE TITLE
Test on OS X

### ISSUE THREAD

**Issue by josephspurrier** [blue-jay/blueprint#36]
Update documentation accordingly.

**Comment by ralic** [comment]
I've tested it on OS X and no issue found so far
# Instructions  :
## Prepare  golang support on macOS
brew install go
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=/usr/local/opt/go/libexec/bin

## Prepare jay-cli support on macOS
git clone https://github.com/blue-jay/jay.git
cd jay
go build 
cp jay /usr/local/bin 

## Quick-start for blue-print 
git clone https://github.com/blue-jay/blueprint.git
go get github.com/blue-jay/jay/
go get github.com/blue-jay/blueprint/
cd blueprint

## Database preparation  ( vi env.json to change MySQL user & password)
export JAYCONFIG=./env.json
jay env make
jay migrate all

## Run the server
go build
sudo ./blueprint
open http://localhost

**Comment by josephspurrier** [comment]
@ralic Awesome! Thanks for the instructions too. I need to add this to a wiki page.

**Comment by josephspurrier** [comment]
I added the instructions to: https://github.com/blue-jay/blueprint/wiki/Blueprint-Setup-for-OS-X.

**Comment by josephspurrier** [comment]
Testing is complete. I added a quick instruction for docker too.

**Comment by josephspurrier** [comment]
I added to the website also: http://blue-jay.github.io/#os-specific-instructions
