### ISSUE TITLE
Quick start - 'go get' git issue - significant typo

### ISSUE THREAD

**Issue by Nemykal** [blue-jay/blueprint#38]
Hi,
I'm doing some quick testing of this project on Linux (Alpine) and ran into an issue with the initial git clone (with go get ...). I was following this: http://blue-jay.github.io/#quick-start-website-with-jay

```
# cd .; git clone https://github.com/blue-ray/blueprint /home/getgood/go/src/github.com/blue-ray/blueprint
Cloning into '/home/getgood/go/src/github.com/blue-ray/blueprint'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/blue-ray/blueprint: exit status 128

```

It looks like the user name is wrong in the quickstart docs :smiley:

**Comment by josephspurrier** [comment]
Ok, less beer after work. Cheers! https://github.com/blue-jay/blue-jay.github.io.hugo/commit/4108508ede77d81b66061b8db7c2e752ce14f1f4
