### ISSUE TITLE
"HTTPPort":80

### ISSUE THREAD

**Issue by nicomo** [blue-jay/blueprint#40]
Not sure it's an "issue", rather feedback, but it's the only small snag I hit when installing: when doing go run blueprint I got an error: listen tcp :80: bind: permission denied.
Because by default the env.json file has "HTTPPort":80 and I wasn't running it as root.
I ended up editing env.json to bump HTTPPort to 8080.

**Comment by josephspurrier** [comment]
Thanks, yeah. I'll update the documentation and wiki to reflect that.

**Comment by josephspurrier** [comment]
Instructions updated here: https://github.com/blue-jay/blueprint/wiki/Blueprint-Setup-for-OS-X

**Comment by josephspurrier** [comment]
Added to website: https://github.com/blue-jay/blue-jay.github.io.hugo/commit/3e7bc3a5e240508c4caf75dde882dcf76d41f961

http://blue-jay.github.io/#os-specific-instructions

Does that work?

**Comment by nicomo** [comment]
It does. Thanks.
