### ISSUE TITLE
Wiki: use of $GOPATH 

### ISSUE THREAD

**Issue by juame** [blue-jay/blueprint#43]
Not sure how I can put this into the project. It might not be an issue:
I was thinking about if it would make sense to use $GOPATH instead of the fullpath in the examples of the wiki?

So, instead of
```bash
export JAYCONFIG=$HOME/godev/workspace/src/github.com/blue-jay/blueprint/env.json
```
just:
```bash
export JAYCONFIG=$GOPATH/src/github.com/blue-jay/blueprint/env.json
```
Thanks!

**Comment by josephspurrier** [comment]
Yep, that does make sense. I updated all the OS pages in the Wiki: https://github.com/blue-jay/blueprint/wiki

**Comment by josephspurrier** [comment]
Thanks!
