### ISSUE TITLE
Controller code generation templates have incorrect import path for acl middleware.

### ISSUE THREAD

**Issue by benjmarshall** [blue-jay/blueprint#44]
The 'default.gen' and 'noflight.gen' templates both include imports for:
`    "github.com/blue-jay/blueprint/lib/middleware/acl"`

This results in 'cannot find package' build errors in the generated code.

The include paths should be corrected to:
`    "github.com/blue-jay/blueprint/middleware/acl"`

I.e. remove the '/lib' element.

**Comment by josephspurrier** [comment]
Yep, good catch. I need to create tests for the templates to ensure they work properly as I refactor.

**Comment by josephspurrier** [comment]
Thanks!
