### ISSUE TITLE
How do you run watcher

### ISSUE THREAD

**Issue by torniker** [blue-jay/blueprint#47]
How do you run blueprint so that on every file change it will rebuild and rerun?

**Comment by josephspurrier** [comment]
I haven't use this, but it looks like it would work well: https://github.com/githubnemo/CompileDaemon.

**Comment by stowelly** [comment]
just submitted a pull request that may address this: https://github.com/blue-jay/blueprint/pull/55

**Comment by josephspurrier** [comment]
How does this work for you? https://github.com/blue-jay/blueprint/commit/9e33d14e79a610e4135c675542e74ec30fd4a957

Just run: gulp watch

**Comment by josephspurrier** [comment]
I merged this in. Let me know if you have any issues!
