### ISSUE TITLE
generation templates, issue with "nameonly"

### ISSUE THREAD

**Issue by arapov** [blue-jay/blueprint#51]
Hi,

the commit 1d9c7e1229328c02b7548f33e55ee6cd98ad2a5c has introduced **model/nameonly** and **controller/nameonly** though nameonly doesn't exist, it was removed by the very commit.

this is trivial, though makes generating crud impossible.
pull request #52 

Anton.

**Comment by josephspurrier** [comment]
Fixed by https://github.com/blue-jay/blueprint/pull/52
