### ISSUE TITLE
Need to know how we can create middleware for Admin/Seller/Buyer for a bidding website

### ISSUE THREAD

**Issue by cisaman** [blue-jay/blueprint#54]
Need to know how we can create middleware for Admin/Seller/Buyer for a bidding website
Also need to know to prefix the routes and separate login and template for Admin.

**Comment by josephspurrier** [comment]
You can see two examples of middleware here: https://github.com/blue-jay/blueprint/blob/master/middleware/acl/acl.go

The documentation for middleware is here: https://blue-jay.github.io/middleware/
