### ISSUE TITLE
Sass compiles to separate files instead of all.css

### ISSUE THREAD

**Issue by lansana** [blue-jay/blueprint#60]
1. Which commit are you using?
The most recent version

2. Which operating system, processor architecture, and Go version are you using (`go env`)?
Mac, latest Go version, Intel core m7

3. What did you do?
Created separate sass files, such as foo.scss, bar.scss and baz.scss

4. What did you expect to see?
Expected them all to be concatenated into all.css

5. What did you actually see?
Got foo.css, bar.css, baz.css (which requires me to add them all into the <head> individually, which could be bad if there were 100 stylesheets for example because that would be 100 more requests on page load, as opposed to having them all in all.css for one request on page load.

The process works perfectly for the javascript task as it concatenates everything into all.min.js.

**Comment by josephspurrier** [comment]
You should store your styles as partials and then import them at the top of all.scss.
