### ISSUE TITLE
How to disable CSRF on API modules?

### ISSUE THREAD

**Issue by v2tmobile** [blue-jay/blueprint#63]
1. Which commit are you using?
[e65ca2b](https://github.com/blue-jay/blueprint/commit/e65ca2be88e353b2bad9c57b1c3c8f2e0e2a46ff)

2. Which operating system, processor architecture, and Go version are you using (`go env`)?
Mac OS X 10.12.4
Golang 1.7.5

3. What did you do?
Create new module to implement Restful API

4. What did you expect to see?
Disable CSRF on only API module

5. What did you actually see?
Every POST request require a valid CSRF token

**Comment by josephspurrier** [comment]
You can disable the CSRF completely from here - if you only want to apply it to certain routes, you can change the handlers around so only certain middleware apply to certain routes:
https://github.com/blue-jay/blueprint/blob/master/lib/boot/middleware.go#L17

All the settings for CSRF can be set here:
https://github.com/blue-jay/blueprint/blob/master/lib/boot/xsrf.go#L25

**Comment by v2tmobile** [comment]
Thank you, so I must disable the CSRF completely then apply it to certain routes that I want to handle CSRF?

**Comment by josephspurrier** [comment]
Yes, that is correct.
