### ISSUE TITLE
Hello, Can I using the memcached within this web package?

### ISSUE THREAD

**Issue by cccculb** [blue-jay/blueprint#70]
Please answer these questions when submitting your issue. Thanks!

1. Which commit are you using?
I have not using the commit.

2. Which operating system, processor architecture, and Go version are you using (`go env`)?
OS : windows and linux (centos) 
process : x64
go version : 1.92

3. What did you do?
I am first using use form golang. I found a full package and was very excited.
How can use the Memcached in this package?

4. What did you expect to see?
I want to merge the session.go with memcached.

5. What did you actually see?
I have no idea.

**Comment by josephspurrier** [comment]
Take a look at this package: https://github.com/bradleypeabody/gorilla-sessions-memcache

[Session.go](https://github.com/blue-jay/core/blob/master/session/session.go) is just a wrapper around [gorilla/sessions](https://github.com/gorilla/sessions).
