### ISSUE TITLE
How to customize project name?

### ISSUE THREAD

**Issue by whitesnow9291** [blue-jay/blueprint#71]
When I install this project, it create project with name blueprint.
I hope to customize project name.
If I change blueprint to other name, it makes so many errors when I run.
Looking forward to hearing from you soon.
Best Regards.

**Comment by josephspurrier** [comment]
I would use the jay replace command:
`jay replace . "blue-jay/blueprint" "user/project"`

Source: https://blue-jay.github.io/find-replace/#find-and-replace-examples
