### ISSUE TITLE
Foreach in a view ?

### ISSUE THREAD

**Issue by aquint-g** [blue-jay/blueprint#76]
I'm sure i'm missing something but i can't find a way to parse easily my arrays in a view.

For instance i want to list every users registered on my webapp. I'm able to get them form the database, push them to the view.. But I'm only able to print a JSON of the items.

Isn't there a way to do something like a foreach in tpml files ?

Thanks in advance

**Comment by josephspurrier** [comment]
Yes, you can loop through the items like this:

https://github.com/blue-jay/blueprint/blob/master/view/note/index.tmpl#L13

```go
{{range $n := .items}}
    <p>{{.Name}}</p>
{{end}}
```
